version: '3'

services:

  # database containers, one for each db
  database1:
    image: postgres:13.7-alpine3.160
    volumes:
      - database1_volume:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - database1_network

  # web container, with django + gunicorn
  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
    networks:
      - database1_network
      - nginx_network
    depends_on:
      - database1

  # reverse proxy container (nginx)
  nginx:
    image: nginx:stable
    ports:
      - 8000:80
    volumes:
      - ./config/:/etc/nginx/conf.d
    env_file:
      - .env
    networks:
      - nginx_network
    depends_on:
      - djangoapp

networks:
  database1_network:
    driver: bridge
  database2_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  database1_volume: