# Generated by Django 4.0.6 on 2022-08-02 13:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=250)),
                ('version', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(choices=[("<class 'Core.Rules.FeatureFules.GlobalRule'>", 'Global'), ("<class 'Core.Rules.FeatureFules.PartialRule'>", 'Partial'), ("<class 'Core.Rules.FeatureFules.MinimumRule'>", 'Minimum'), ("<class 'Core.Rules.FeatureFules.MinimumPartialRule'>", 'Minimumpartial')], default="<class 'Core.Rules.FeatureFules.GlobalRule'>", max_length=120)),
                ('Function', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule', to='Core.functions')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.IntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.rule')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
