# Generated by Django 4.0.6 on 2022-08-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rule', models.IntegerField(choices=[("<class 'Core.Rules.FeatureFules.GlobalRule'>", 'Global'), ("<class 'Core.Rules.FeatureFules.PartialRule'>", 'Partial'), ("<class 'Core.Rules.FeatureFules.MinimumRule'>", 'Minimum'), ("<class 'Core.Rules.FeatureFules.MinimumPartialRule'>", 'Minimumpartial')], default="<class 'Core.Rules.FeatureFules.GlobalRule'>", max_length=100)),
                ('functions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_function', related_query_name='user_function_query', to='Core.functions')),
            ],
        ),
    ]
