# Generated by Django 4.0.6 on 2022-08-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_feature_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rule',
        ),
    ]
